--Ejercicio 1--
SELECT count(NOMBRE_ESTACION) FROM barcelona_viajeros_por_franja_xlsx 

--Ejercicio 2--
SELECT DISTINCT NOMBRE_ESTACION FROM barcelona_viajeros_por_franja_xlsx 
--distint es te muestra solo un nombre sin repetir--

--Ejercicio 3--
SELECT NOMBRE_ESTACION, count(VIAJEROS_BAJADOS) as PASAJEROS_BAJADOS , count(VIAJEROS_SUBIDOS) as PASAJEROS_SUBIDOS 
FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION 
ORDER BY PASAJEROS_BAJADOS,PASAJEROS_SUBIDOS DESC

--Ejercicio 4--
SELECT NOMBRE_ESTACION,sum(VIAJEROS_SUBIDOS) as PASAJEROS_SUBIDOS, sum(VIAJEROS_BAJADOS) as PASAJEROS_BAJADOS ,abs(sum(VIAJEROS_BAJADOS) - sum(VIAJEROS_SUBIDOS)) as DIFERENCIA_ENTRE_PByPS 
FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION 
ORDER by PASAJEROS_SUBIDOS DESC
--Ejercicio 5--

SELECT NOMBRE_ESTACION,max(VIAJEROS_SUBIDOS) as PASAJEROS_SUBIDOS, TRAMO_HORARIO 
FROM barcelona_viajeros_por_franja_xlsx
GROUP by TRAMO_HORARIO
ORDER by PASAJEROS_SUBIDOS DESC

--Ejercicio 6--
SELECT NOMBRE_ESTACION,max(VIAJEROS_SUBIDOS) as PASAJEROS_SUBIDOS ,TRAMO_HORARIO 
FROM barcelona_viajeros_por_franja_xlsx

--Ejercicio 7--
SELECT NOMBRE_ESTACION, max(VIAJEROS_BAJADOS) as PASAJEROS_BAJADOS ,TRAMO_HORARIO 
FROM barcelona_viajeros_por_franja_xlsx 
GROUP by TRAMO_HORARIO
ORDER BY PASAJEROS_BAJADOS DESC

--Ejercicio 8--
SELECT NOMBRE_ESTACION, max(VIAJEROS_BAJADOS) as PASAJEROS_BAJADOS ,TRAMO_HORARIO 
FROM barcelona_viajeros_por_franja_xlsx

--Ejercicio 9--
SELECT NOMBRE_ESTACION, VIAJEROS_BAJADOS, VIAJEROS_SUBIDOS ,abs(VIAJEROS_BAJADOS - VIAJEROS_SUBIDOS) as DIFERENCIA_ENTRE_PByPS, TRAMO_HORARIO FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY DIFERENCIA_ENTRE_PByPS DESC
LIMIT 1
--abs:pasa valores a positivo--

--Ejercicio 10--
SELECT NOMBRE_ESTACION,sum(VIAJEROS_SUBIDOS) as PASAJEROS_SUBIDOS, sum(VIAJEROS_BAJADOS) as PASAJEROS_BAJADOS ,abs(sum(VIAJEROS_BAJADOS) - sum(VIAJEROS_SUBIDOS)) as DIFERENCIA_ENTRE_PByPS 
FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION 
ORDER by PASAJEROS_SUBIDOS DESC
LIMIT 1 

--Ejercicio 11--
SELECT round(avg(VIAJEROS_SUBIDOS), 2) as PROMEDIO_PS ,round(avg(VIAJEROS_BAJADOS), 2) as PROMEDIO_PB ,TRAMO_HORARIO
FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY TRAMO_HORARIO DESC

--Ejercicio 12--
SELECT NOMBRE_ESTACION, round(avg(VIAJEROS_BAJADOS), 2) as PROMEDIO_PB,round(avg(VIAJEROS_SUBIDOS), 2) as PROMEDIO_PS ,TRAMO_HORARIO
FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY TRAMO_HORARIO DESC